# Generated by Django 4.0.4 on 2022-05-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_image', models.ImageField(upload_to='blog_images/')),
                ('blog_text', models.TextField()),
                ('blog_title', models.CharField(max_length=300)),
                ('blog_date', models.DateField()),
            ],
        ),
    ]
